<?php
// See https://github.com/shuchkin/simplexlsxgen/tree/master
use Shuchkin\SimpleXLSXGen;

require_once 'config.php';
require_once 'User.php';
require_once 'Input.php';
require_once 'BookingClass.php';
require_once 'SimpleXLSXGen.php';

// Format amount for in spreadsheet
function format_amount($amount) {
	return '<right>'.html_entity_decode(PM_CURRENCY).' '.number_format($amount, 2, ',', '.').'</right>';
}

// Generate a worksheet, we can pass an extra function to calulate extra column.
function generate_worksheet($prefix, $columns, $submitted, $sql = null, $extra_function = null) {
	global $booking, $xlsx, $db, $clubs;
	// Set sql statement to default if not passed. We must use the submitted tables.
	$tab_name = $prefix;
	if ($submitted) { $tab_name .= SUBMITTED_POSTFIX; }
	$sql = ($sql) ? $sql : 'SELECT * FROM '.$tab_name.' ORDER BY `booking_id`;';
	// Build sql column names and sheet header row
	$row = array();
	foreach($columns as $column) {
		$row[] = '<b>'.ucfirst(str_replace('_', ' ', $column)).'</b>';
    // Insert Clubname after (booking_)id as applicable
    if (($prefix == BOOKING_PREFIX and $column == 'id') OR ($prefix != CONTACT_PREFIX and $column == 'booking_id')) {
      $row[] = '<b>Club Name</b>';
    }
	}
	$num_columns = count($row);
	$data[] = $row;
	$rows = 0;
	$db->query_columns($sql, $columns);
	if (!$db->error() AND $db->count() != 0) {
		$t_booking = new Booking();
		foreach ($db->results() as $idx => $item) {
			$itm = get_object_vars($item);
			$row = array();
			foreach($columns as $column) {
				if ($column == 'room_no') {
					$row[] = $booking->hotel_rooms->getHotelRoomByID($itm[$column]);
				} else {
					$row[] = $itm[$column];
				}
        // Add Club name after booking ID as applicable
        if (($prefix == BOOKING_PREFIX and $column == 'id') OR ($prefix != CONTACT_PREFIX and $column == 'booking_id')) {
          $row[] = getSaveArray($clubs, $itm[$column]);
        }
			}
			$data[] = $row;
			$rows++;
		}
	}
	$xlsx->addSheet($data, ucfirst($prefix));
	$xlsx->freezePanes('C2');
	$xlsx->autoFilter('A1:'.chr(64 + $num_columns)."{$rows}");
}

// Overview details as first worksheet
function generate_overview_worksheet($submitted) {
	global $booking, $xlsx, $user;
	$sheet_name = 'Overview';
	// Get all data and add to xlsx
	$booking_data = $booking->collectOverviewDetails(($submitted) ? 'Y':'N');
	$data = array();
	$data[] = array('<style font-size="32">Overview of booking data '.SITE_TITLE_SHORT.'</style>', null);
	$data[] = array('');
	$data[] = array('');
	$data[] = array('Generated on', date('d-M-Y'));
	$data[] = array('Generated by', $user->name());
	// Get statistics
	if ($submitted) {
		$data[] = array('Data set', 'Submitted bookings details only');
		$data[] = array('');
		$data[] = array('<b>Item</b>', '<b><right>Total of submitted</right></b>');
		$index = 2;
	} else {
		$data[] = array('Data set', 'All bookings details saved.');
		$data[] = array('');
		$data[] = array('<b>Item</b>', '<b><right>Total of saved</right></b>');
		$index = 1;
	}
	$data[] = array($booking_data['total_charges'][0], format_amount($booking_data['total_charges'][$index]));
	$data[] = array('');
	$data[] = $booking_data[USERS_PREFIX];
	$data[] = $booking_data[USERS_PREFIX.'act'];
	$data[] = array('');
	$data[] = array($booking_data[BOOKING_PREFIX][0], $booking_data[BOOKING_PREFIX][$index]);
	$data[] = array($booking_data[DELEGATE_PREFIX][0], $booking_data[DELEGATE_PREFIX][$index]);
	$data[] = array($booking_data[GUEST_PREFIX][0], $booking_data[GUEST_PREFIX][$index]);
	$data[] = array($booking_data[PARTY_PREFIX][0], $booking_data[PARTY_PREFIX][$index]);
	$data[] = array($booking_data[GUEST_PREFIX.'ct'][0], $booking_data[GUEST_PREFIX.'ct'][$index]);
	if ($booking->rooms->getEnabled()) {
		foreach(OPTIONS_ROOM_TYPES as $id => $name) {
			$idx = ROOM_PREFIX.$id;
			$data[] = array($booking_data[$idx][0], $booking_data[$idx][$index]);
		}
	}
	if ($booking->travels->getEnabled()) {
		$data[] = array($booking_data[TRAVEL_PREFIX.'arr'][0], $booking_data[TRAVEL_PREFIX.'arr'][$index]);
		$data[] = array($booking_data[TRAVEL_PREFIX.'dep'][0], $booking_data[TRAVEL_PREFIX.'dep'][$index]);
	}
	$data[] = array($booking_data[TSHIRT_PREFIX.'tot'][0], $booking_data[TSHIRT_PREFIX.'tot'][$index]);
	foreach(OPTIONS_TSHIRTS_SIZES as $id => $size) {
		if ($id != 'No shirt') {
			$idx = TSHIRT_PREFIX.str_replace(' ', '', $id);
			$data[] = array($booking_data[$idx][0], $booking_data[$idx][$index]);
		}
	}
	$data[] = array('');
	if ($submitted) {
		$data[] = array('The details worksheets show the submitted data, no unsubitted bookings or changes users may have made.');
	} else {
		$data[] = array('The details worksheets show the saved data, including changes users may have made after submitting their booking.');
	}
	$xlsx->addSheet($data, $sheet_name);
}

// Bookings summary overview worksheet
function generate_bookings_overview_worksheet($submitted) {
	global $booking, $xlsx, $db;
	$sheet_name = 'Bookings Overview';
	$table_postfix = '';
	if ($submitted) {
		$table_postfix = SUBMITTED_POSTFIX;
	}
	$data = array();
	$row = array();
	$row[] = '<b>Booking Ref</b>';
	$row[] = '<b>Club Name</b>';
	$row[] = '<b>User Name</b>';
	$row[] = '<b>Contact Name</b>';
	$row[] = '<b>Submitted</b>';
	$row[] = '<b># Delegates</b>';
	$row[] = '<b># Guests</b>';
	$row[] = '<b># Party</b>';
	$row[] = '<b># t-Shirts</b>';
	$row[] = '<b># City tour</b>';
	if ($booking->rooms->getEnabled()) {
		$row[] = '<b># Rooms</b>';
		if ($booking->travels->getEnabled()) {
			$row[] = '<b># Arr Trans.</b>';
			$row[] = '<b># Dep Trans.</b>';
		}
	}
	$row[] = '<b>Charges</b>';
	$row[] = '<b>Paid</b>';
	$row[] = '<b>Due</b>';
	$data[] = $row;
	$num_columns = count($row);

	// Get all bookings
	$sql = 'SELECT id, user_id, creation_date, modified_date, submitted_date, submitted_count, additional_descr, additional_costs, comments, is_locked FROM '.BOOKING_PREFIX.$table_postfix.' ORDER BY id;';
	$db->query($sql);
	if ($db->error() OR $db->count() == 0) {
		$data[] = array('Unable to read booking data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$bookings = $db->results();
	// Get club and contact names
	$sql = 'SELECT booking_id, club_name, CONCAT(first_name, " ",last_name) as name FROM '.CONTACT_PREFIX.$table_postfix.';';
	$db->query($sql);
	if ($db->error() OR $db->count() == 0) {
		$data[] = array('Unable to read booking contact data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$clubs = array();
	foreach($db->results() as $id => $item) {
		$clubs[$item->booking_id] = array($item->club_name, $item->name);
	}
	// Get users
	$sql = 'SELECT id, name FROM '.USERS_PREFIX.';';
	$db->query($sql);
	if ($db->error() OR $db->count() == 0) {
		$data[] = array('Unable to read booking users data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$users = array();
	foreach($db->results() as $id => $item) {
		$users[$item->id] = $item->name;
	}
	// Get # Delegates
	$sql = 'SELECT booking_id, COUNT(*) AS count FROM '.DELEGATE_PREFIX.$table_postfix.' GROUP BY booking_id;';
	$db->query($sql);
	if ($db->error()) {
		$data[] = array('Unable to read booking delegates data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$delegates = array();
	foreach($db->results() as $id => $item) {
		$delegates[$item->booking_id] = $item->count;
	}
	// Get # Guests
	$sql = 'SELECT booking_id, COUNT(*) AS count FROM '.GUEST_PREFIX.$table_postfix.' GROUP BY booking_id;';
	$db->query($sql);
	if ($db->error()) {
		$data[] = array('Unable to read booking guests data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$guests = array();
	foreach($db->results() as $id => $item) {
		$guests[$item->booking_id] = $item->count;
	}
	// Get # party
	$sql = 'SELECT booking_id, COUNT(*) AS count FROM (SELECT booking_id, party FROM '.DELEGATE_PREFIX.$table_postfix.' UNION ALL SELECT booking_id, party FROM '.GUEST_PREFIX.$table_postfix.') AS combined_tables WHERE party = "Y" GROUP BY booking_id;';
	$db->query($sql);
	if ($db->error()) {
		$data[] = array('Unable to read booking party data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$party = array();
	foreach($db->results() as $id => $item) {
		$party[$item->booking_id] = $item->count;
	}
	// Get # t-Shirt
	$sql = 'SELECT booking_id, COUNT(*) AS count FROM (SELECT booking_id, shirt_size FROM '.DELEGATE_PREFIX.$table_postfix.' UNION ALL SELECT booking_id, shirt_size FROM '.GUEST_PREFIX.$table_postfix.') AS combined_tables WHERE shirt_size != "No shirt" GROUP BY booking_id;';
	$db->query($sql);
	if ($db->error()) {
		$data[] = array('Unable to read booking t-Shirt data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$tshirts = array();
	foreach($db->results() as $id => $item) {
		$tshirts[$item->booking_id] = $item->count;
	}
	// Get # City tour
	$sql =  'SELECT booking_id, COUNT(*) AS count FROM '.GUEST_PREFIX.$table_postfix.' WHERE city_tour = "Y" GROUP BY booking_id;';
	$db->query($sql);
	if ($db->error()) {
		$data[] = array('Unable to read booking city tour data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$citytours = array();
	foreach($db->results() as $id => $item) {
		$citytours[$item->booking_id] = $item->count;
	}
	if ($booking->rooms->getEnabled()) {
		// Get # Rooms
		$sql = 'SELECT booking_id, COUNT(*) AS count FROM '.ROOM_PREFIX.$table_postfix.' GROUP BY booking_id;';
		$db->query($sql);
		if ($db->error()) {
			$data[] = array('Unable to read booking rooms data');
			$xlsx->addSheet($data, $sheet_name);
			return false;
		}
		$rooms = array();
		foreach($db->results() as $id => $item) {
			$rooms[$item->booking_id] = $item->count;
		}
		if ($booking->travels->getEnabled()) {
			// Get # Travels
			$sql = 'SELECT booking_id, SUM(arr_amount) AS count FROM '.TRAVEL_PREFIX.$table_postfix.' WHERE arr_type = "PLANE" GROUP BY booking_id;';
			$db->query($sql);
			if ($db->error()) {
				$data[] = array('Unable to read booking travels data');
				$xlsx->addSheet($data, $sheet_name);
				return false;
			}
			$arr_trav = array();
			foreach($db->results() as $id => $item) {
				$arr_trav[$item->booking_id] = $item->count;
			}
			$sql = 'SELECT booking_id, SUM(dep_amount) AS count FROM '.TRAVEL_PREFIX.$table_postfix.' WHERE dep_type = "PLANE" GROUP BY booking_id;';
			$db->query($sql);
			if ($db->error()) {
				$data[] = array('Unable to read booking travels data');
				$xlsx->addSheet($data, $sheet_name);
				return false;
			}
			$dep_trav = array();
			foreach($db->results() as $id => $item) {
				$dep_trav[$item->booking_id] = $item->count;
			}
		}
	}
	$rows = 0;
	// Populate data
	$t_booking = new Booking;
	foreach ($bookings as $bid => $bkng) {
		$row = array();
		$id = $bkng->id;
		$row[] = number_format($id) . '-' . number_format($bkng->submitted_count);
		//$row[] = $t_booking->getReference($id, $bkng->submitted_count);
		if (array_key_exists($id, $clubs)) { $row[] = $clubs[$id][0]; } else { $row[]='?';}
		if (array_key_exists($bkng->user_id, $users)) { $row[] = $users[$bkng->user_id]; } else { $row[]='?';}
		if (array_key_exists($id, $clubs)) { $row[] = $clubs[$id][1]; } else { $row[]='?';}
		$row[] = $bkng->submitted_date;
		if (array_key_exists($id, $delegates)) {$row[] = $delegates[$id]; } else { $row[]='0';}
		if (array_key_exists($id, $guests)) {$row[] = $guests[$id]; } else { $row[]='0';}
		if (array_key_exists($id, $party)) {$row[] = $party[$id]; } else { $row[]='0';}
		if (array_key_exists($id, $tshirts)) {$row[] = $tshirts[$id]; } else { $row[]='0';}
		if (array_key_exists($id, $citytours)) {$row[] = $citytours[$id]; } else { $row[]='0';}
		if ($booking->rooms->getEnabled()) {
			if (array_key_exists($id, $rooms)) {$row[] = $rooms[$id]; } else { $row[]='0';}
			if ($booking->travels->getEnabled()) {
				if (array_key_exists($id, $arr_trav)) {$row[] = $arr_trav[$id]; } else { $row[]='0';}
				if (array_key_exists($id, $dep_trav)) {$row[] = $dep_trav[$id]; } else { $row[]='0';}
			}
		}
		// Add financials.
		$total = $t_booking->totalCharges($id, $submitted);
		$paid = $t_booking->totalPayments($id);
		$row[] = format_amount($total);
		$row[] = format_amount($paid);
		$row[] = format_amount($total - $paid);

		$data[] = $row;
		$rows++;
	}
	$xlsx->addSheet($data, $sheet_name);
	$xlsx->freezePanes('C2');
	$xlsx->autoFilter('A1:'.chr(64 + $num_columns)."{$rows}");
}

// details for reception/bags
function generate_reception_worksheet($submitted) {
	global $booking, $xlsx, $db, $clubs;
	$sheet_name = 'Bags';
	$table_postfix = '';
	if ($submitted) {
		$table_postfix = SUBMITTED_POSTFIX;
	}
	$data = array();
	$row = array();
	$row[] = '<b>Booking ID</b>';
	$row[] = '<b>Club Name</b>';
	$row[] = '<b>Name</b>';
	$row[] = '<b>Type</b>';
	$row[] = '<b>t-Shirt</b>';
	$row[] = '<b>Party</b>';
	$row[] = '<b>City Tour</b>';
	if ($booking->rooms->getEnabled()) {
		$row[] = '<b>Room type</b>';
		$row[] = '<b>Room number</b>';
	}
	$data[] = $row;
	$num_columns = count($row);
  // Get rooms details
	$sql = 'SELECT booking_id, type, room_no, guest1, guest2 FROM '.ROOM_PREFIX.$table_postfix.';';
	$db->query($sql);
	if ($db->error() OR $db->count() == 0) {
		$data[] = array('Unable to read room data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$rooms = $db->results();
	$sql = 'SELECT DISTINCT d.booking_id, "Delegate" as dtype, last_name, CONCAT(first_name, " ",last_name) as name, shirt_size, party, "" as city_tour
		FROM '.DELEGATE_PREFIX.$table_postfix.' AS d
		UNION
		SELECT DISTINCT d.booking_id, "Guest" as dtype, last_name, CONCAT(first_name, " ",last_name) as name, shirt_size, party, city_tour
		FROM '.GUEST_PREFIX.$table_postfix.' AS d
		ORDER BY booking_id, last_name;';
	$db->query($sql);
	if ($db->error() OR $db->count() == 0) {
		$data[] = array('Unable to read database.');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$rows = 0;
	foreach ($db->results() as $idx => $item) {
		$row = array();
		$row[] = $item->booking_id;
		$row[] = getSaveArray($clubs, $item->booking_id); // Club name
		$row[] = $item->name;
		$row[] = $item->dtype;
		$row[] = $item->shirt_size;
		$row[] = $item->party;
		$row[] = $item->city_tour;
		if ($booking->rooms->getEnabled()) {
      foreach($rooms as $id => $room) {
        if ($item->booking_id == $room->booking_id) {
          if ((isset($room->guest1) AND (strtolower($room->guest1) == strtolower($item->name))) OR (isset($room->guest2) and (strtolower($room->guest2) == strtolower($item->name)))) {
            $row[] = $room->type;
            $row[] = $booking->hotel_rooms->getHotelRoomByID($room->room_no);
          }
        }
      }
		}
		$data[] = $row;
		$rows++;
	}
	$xlsx->addSheet($data, $sheet_name);
	$xlsx->freezePanes('C2');
	$xlsx->autoFilter('A1:'.chr(64 + $num_columns)."{$rows}");
}

// Generate worksheet for delegate name labels
function generate_nametag_worksheet($submitted){
	global $xlsx, $db, $clubs;
	$sheet_name = 'Tags';
	$data = array();
	$data[] = array('Booking ID', 'Club Name', 'Name', 'Position');
	$table_postfix = '';
	if ($submitted) {
		$table_postfix = SUBMITTED_POSTFIX;
	}
	$sql = 'SELECT booking_id, CONCAT(first_name, " ",last_name) as name, position FROM '.DELEGATE_PREFIX.$table_postfix.' ORDER BY booking_id;';
	$db->query($sql);
	if ($db->error() OR $db->count() == 0) {
		$data[] = array('Unable to read booking data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$rows = 0;
	$num_columns = 4;
	foreach ($db->results() as $idx => $item) {
		$row = array();
		$row[] = $item->booking_id;
		$row[] = getSaveArray($clubs, $item->booking_id); // Club name
		$row[] = $item->name;
		$row[] = $item->position;
		$data[] = $row;
		$rows++;
	}
	
	$xlsx->addSheet($data, $sheet_name);
	$xlsx->freezePanes('B2');
	$xlsx->autoFilter('A1:'.chr(64 + $num_columns)."{$rows}");
}

// Generate worksheet for city tour
function generate_citytour_worksheet($submitted){
	global $xlsx, $db, $clubs;
	$sheet_name = 'City Tour';
	$data = array();
	$data[] = array('Booking ID', 'Club Name', 'Name');
	$table_postfix = ($submitted) ? SUBMITTED_POSTFIX:'';
	$sql = 'SELECT booking_id, CONCAT(first_name, " ",last_name) as name, city_tour FROM '.GUEST_PREFIX.$table_postfix.' WHERE city_tour = "Y" ORDER BY booking_id;';
	$db->query($sql);
	if ($db->error() OR $db->count() == 0) {
		$data[] = array('Unable to read city tour data, or no applicants.');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$rows = 0;
	$num_columns = 3;
	foreach ($db->results() as $idx => $item) {
		$row = array();
		$row[] = $item->booking_id;
		$row[] = getSaveArray($clubs, $item->booking_id); // Club name
		$row[] = $item->name;
		$data[] = $row;
		$rows++;
	}
	
	$xlsx->addSheet($data, $sheet_name);
	$xlsx->freezePanes('B2');
	$xlsx->autoFilter('A1:'.chr(64 + $num_columns)."{$rows}");
}

// Generate worksheet listing all known FH-DCE clubs and if they have a booking
function generate_fhdce_clubs_worksheet($submitted){
	global $xlsx, $db;
	$sheet_name = 'FH-DCE Clubs';
	$table_postfix = '';
	if ($submitted) {
		$table_postfix = SUBMITTED_POSTFIX;
	}
	$data = array();
	$data[] = array('Club ID', 'Club Name', 'CC', 'Booking_ID', 'Submitted Date');
	$sql = 'SELECT id, name, cc FROM '.FHDCE_CLUBS_PREFIX.' ORDER BY name;';
	$db->query($sql);
	if ($db->error() OR $db->count() == 0) {
		$data[] = array('Unable to read club data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$fh_clubs = $db->results();
	$sql = 'SELECT id, submitted_date FROM '.BOOKING_PREFIX.$table_postfix.';';
	$db->query($sql);
	if ($db->error() OR $db->count() == 0) {
		$data[] = array('Unable to read booking data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$bookings = $db->results();
	$sql = 'SELECT booking_id, club_name FROM '.CONTACT_PREFIX.$table_postfix.';';
	$db->query($sql);
	if ($db->error() OR $db->count() == 0) {
		$data[] = array('Unable to read booking data');
		$xlsx->addSheet($data, $sheet_name);
		return false;
	}
	$contacts = $db->results();
	$rows = 0;
	$num_columns = 6;
	foreach ($fh_clubs as $idx => $item) {
		// Find club booking using contacts
		$booking_id = null;
		$sub_date = null;
		foreach ($contacts as $idxx => $contact) {
			if ($contact->club_name == $item->name) {
				$booking_id = $contact->booking_id;
				break;
			}
		}
		if ($booking_id != null) {
			foreach ($bookings as $idxx => $booking) {
				if ($booking->id == $booking_id) {
					$sub_date = $booking->submitted_date;
					break;
				}
			}
		}
		$row = array();
		$row[] = $item->id;
		$row[] = $item->name;
		$row[] = $item->cc;
		$row[] = $booking_id;
		$row[] = $sub_date;
		$data[] = $row;
		$rows++;
	}
	
	$xlsx->addSheet($data, $sheet_name);
	$xlsx->freezePanes('B2');
	$xlsx->autoFilter('A1:'.chr(64 + $num_columns)."{$rows}");
}

$table_postfix = '';
$booking = new Booking();
$xlsx = new SimpleXLSXGen();
$user = new User();
  
if(!$user->isLoggedIn() OR !$user->isActive() OR !$user->isAdmin()) {
	// We do not have the user_id in the session, redirect to logon page
    postReturn('Session expired. Logon again.', 'error', true);
	exit;
}
if(!Input::exists()) {
    postReturn('Unknown error (no form data).', 'error');
	exit;
}
$file_name = Input::Get("file_name");
if ($file_name == '') {
    postReturn('Unknown error (no file_name).', 'error');
	exit;
}
if (Input::Get("submitted_only") == 'Y') {
	$table_postfix = SUBMITTED_POSTFIX;
	$submitted = true;
} else {
	$submitted = false;
}
$xlsx->setAuthor(htmlspecialchars(PM_ORGANIZER))->setTitle(SITE_TITLE_SHORT . 'Data')->setLanguage('en-US');

$db = Database::getInstance();
// Get club names for multiple sheets
$clubs = $booking->getContactClubNames();

// Generate an export file worksheets of the submitted data.
generate_overview_worksheet($submitted);
generate_bookings_overview_worksheet($submitted);
generate_reception_worksheet($submitted);
generate_nametag_worksheet($submitted);
generate_fhdce_clubs_worksheet($submitted);
generate_worksheet(USERS_PREFIX,  array('id', 'name', 'email', 'active', 'joined', 'last_active'), $submitted, 'SELECT * FROM '.USERS_PREFIX.' WHERE admin = "0" ORDER BY `name`;');
generate_worksheet(BOOKING_PREFIX, BOOKING_FIELDS, $submitted, 'SELECT * FROM '.BOOKING_PREFIX.$table_postfix.' ORDER BY `user_id`;');
// special worksheets
generate_worksheet("party", array('booking_id', 'first_name', 'last_name'), $submitted, 
	"(SELECT * FROM ".DELEGATE_PREFIX.$table_postfix." WHERE party='Y')\nUNION\n(SELECT * FROM ".GUEST_PREFIX.$table_postfix." WHERE party='Y')\nORDER BY booking_id;");
generate_worksheet("tshirts", array('booking_id', 'first_name', 'last_name','shirt_size'), $submitted, 
	"(SELECT * FROM ".DELEGATE_PREFIX.$table_postfix." WHERE shirt_size!='No shirt')\nUNION\n(SELECT * FROM ".GUEST_PREFIX.$table_postfix." WHERE shirt_size!='No shirt')\nORDER BY booking_id,shirt_size;");
generate_citytour_worksheet($submitted);
if ($booking->travels->getEnabled()) {
	generate_worksheet("arr_transfers", array('booking_id', 'arr_airport', 'arr_flight_no', 'arr_date', 'arr_time', 'arr_amount'), $submitted, 
		"SELECT * FROM ".TRAVEL_PREFIX.$table_postfix." WHERE arr_type='PLANE' ORDER BY arr_date,arr_time;");
	generate_worksheet("dep_transfers", array('booking_id', 'dep_airport', 'dep_flight_no', 'dep_date', 'dep_time', 'dep_amount'), $submitted, 
		"SELECT * FROM ".TRAVEL_PREFIX.$table_postfix." WHERE dep_type='PLANE' ORDER BY dep_date,dep_time;");
	generate_worksheet("arr_hotel", array('booking_id', 'arr_date', 'arr_other'), $submitted, 
		"SELECT * FROM ".TRAVEL_PREFIX.$table_postfix." WHERE arr_type='OTH' ORDER BY arr_date,arr_other;");
	generate_worksheet("dep_hotel", array('booking_id', 'dep_date', 'dep_other'), $submitted, 
		"SELECT * FROM ".TRAVEL_PREFIX.$table_postfix." WHERE dep_type='OTH' ORDER BY dep_date,dep_other;");
}
generate_worksheet(CONTACT_PREFIX, CONTACT_FIELDS, $submitted);
generate_worksheet(DELEGATE_PREFIX, DELEGATE_FIELDS, $submitted);
generate_worksheet(GUEST_PREFIX, GUEST_FIELDS, $submitted);
if ($booking->rooms->getEnabled()) {
	generate_worksheet(ROOM_PREFIX, ROOM_FIELDS, $submitted);
}
if ($booking->travels->getEnabled()) {
	generate_worksheet(TRAVEL_PREFIX, TRAVEL_FIELDS, $submitted);
}
generate_worksheet(PAYMENT_PREFIX, PAYMENT_FIELDS, $submitted, 'SELECT * FROM '.PAYMENT_PREFIX.' ORDER BY `booking_id`;');
	
$xlsx->saveAs($file_name);
// Not getting download to work directly from web page.
//$xlsx->downloadAs($file_name);
postReturn('Export file generated.');
?>
