<!DOCTYPE html >
<?php
require_once 'config.php';
require_once 'Input.php';
require_once 'Redirect.php';
require_once 'User.php';
require_once 'booking_functions.php';
require_once 'email_functions.php';

const PAGE_TITLE = 'Password reset';
?>
<html lang="en">
<head>
	<meta http-equiv="Page-Enter" content="blendTrans(Duration=1.0)">
    <meta http-equiv="content-type" content="text/html;charset=UTF-8">
    <meta http-equiv="Content-Language" content="en">
 	<meta http-equiv="Pragma" content="no-cache">
 	<meta http-equiv="Expires" content="-1">
 	<meta http-equiv="imagetoolbar" content="no">
    <meta charset="UTF-8">
 	<meta name="robots" content="noindex,nofollow">
 	<meta name="creation-date" content="10/01/2025">
 	<meta name="revisit-after" content="50 days">
 	<meta name="author" content="H-DC t Centrum">
 	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="HDCCPM2025.css" rel="stylesheet" type="text/css"> 
    <title><?php echo SITE_TITLE_SHORT.' '.PAGE_TITLE; ?></title>
</head>
<body>
    <div class="container body-background">
        <div class="row g-5" style="margin-left: auto;">
            <div class="col-auto" id="main-contents">
<?php
echo page_header(PAGE_TITLE);

$user = new User();
if($user->isLoggedIn()) {
    $user->logout();
	Redirect::to(SITE_LOGON_PAGE);
} else {
    if(Input::exists()) {
        // We got a post, check and send email if valid.
        if(Input::get('username') != '' AND Input::get('email') != '') {
            $user = new User(Input::get('username'));
            if($user->exists()) { 
                if($user->email() == Input::get('email')) {
                    // Wachtwoord wijzigen, met autogenerated, email verzenden
                    $actcode = $user->generateActivationCode();
                    $body  = '<p>On the '.PM_TITLE.' registration site you requested a new password. ';
                    $body .= 'To change your password and re-activate your account; <a href="'.SITE_NAME.'activate.php?id='.$user->id().'&code='.$actcode.'&reset=true">click here</a>. Or paste this link in your browser: '.SITE_NAME.'activate.php?id='.$user->id().'&code='.$actcode.'&reset=true<br></p>';
                    $body .= '<p>When you DO NOT want change your password, but only re-activate your account; <a href="'.SITE_NAME.'activate.php?id='.$user->id().'&code='.$actcode.'&activate=true">click here</a> Or paste this link in your browser: '.SITE_NAME.'activate.php?id='.$user->id().'&code='.$actcode.'&activate=true.<br></p>';
                    $body .= '<p>** This is an automatic generated message **</p><br>';
                    $body .= '<p>When you did NOT request a password reset, please contact <a href="mailto:'.SITE_EMAIL.'">'.SITE_EMAIL.'</a></p>';
                    $subject =  html_entity_decode(SITE_TITLE).' Change password request';
                    [$mail_res, $msg] = send_email($subject, $user->name(), $body, $user->email());
                    if ($mail_res) {
                        echo '<p><br><br>An email will be send to you by <em><b>"'.html_entity_decode(SITE_TITLE).'&lt;'.SITE_EMAIL.'&gt;"</b></em> with the subject line <em><b>"'.$subject.'"</b></em> within minutes providing the instructions how to set a new password. ';
                        echo 'In this e-mail you will find a link to a page where you can change your password.</p>';
                        echo '<p><br>If you do not see the email, make sure to check your email spam folder, especially if you have a gmail.com, or outlook.com email address. When you did not receive the email, contact '.SITE_EMAIL.'.</p>';
                        echo '<p>&nbsp;<br></p>';
                        echo '<p><br> <br><a href="index.php">&laquo; Go to logon page</a></p>';
                        try {
                          $user->deactivate($actcode);
                        } catch (Exception $e) {    
                          echo '<p><br><br>An error has occurred while activating you account, please try again.</p>';
                          echo $e;
                          echo '<p><a href="javascript:history.back()">&laquo; Go back</a></p>';
                        }
                    } else {    
                        echo "<p><br><br>An error occured while trying to send the email. Your account stays de-activated. <br> <br> ";
                        echo "Please contact the site administrator: <a href=\"mailto:".SITE_EMAIL."\">".SITE_EMAIL."</a> to activate your account.</p>";
                        echo "<p><br><br>Mailer Error: $msg.<p>";
                    }
                } else {
                    echo '<p><br><br>The given email address does not match with the email address for user name '.htmlspecialchars(Input::get('username')).' in our records.</p>';
                    echo '<p><br> <br><a href="javascript:history.back()">&laquo; Go Back</a></p>';
                }
            } else {
                echo '<p><br><br>The user name you entered does not exist in our records.</p><p><br><br><a href="javascript:history.back()">&laquo; Go back</a></p>';
            }
        } else {
            echo '<p><br><br>You did not fill in all the fields correctly. All fields are mandatory.</p><p><br><br><a href="javascript:history.back()">&laquo; Go back</a></p>';
        }
    } else {
  // Formulier
?>
    <p>Enter the user name and email used for the initial account registration to request a password reset.</p>
    <form method="post" action="forgotpass.php" accept-charset="utf-8" class="gy-2 align-items-center">
        <div class="row mb-3">
            <label for="username" class="col-md-3 col-form-label">User name:</label>
            <div class="col-md-6">
                <input type="text" id="username" name="username" class="form-control" autofocus autocomplete="off" required placeholder="Your user name.." minlength="<?=USER_NAME_MIN_LENGTH?>" maxlength="<?=USER_NAME_MAX_LENGTH?>" />
            </div>
        </div>
        <div class="row mb-3">
            <label for="email" class="col-md-3 col-form-label">Email address:</label>
            <div class="col-md-6">
                <input type="email" id="email" name="email" class="form-control" autofocus autocomplete="off" required placeholder="Enter your email address.." minlength="<?=USER_NAME_MIN_LENGTH?>" maxlength="<?=USER_NAME_MAX_LENGTH?>" />
            </div>
        </div>
        <div class="row mb-3">
   	        <label for="submit" class="col-md-3 col-form-label"></label> 
            <div class="d-grid col-md-6">
                <input type="submit" name="submit" class="btn btn-primary" value="Request new password" /> 
            </div>
        </div>
    </form>
<?php
    }
}
?>
            </div> <!-- id="main-contents" -->
        </div> <!-- class row -->
    </div> <!-- class .container -->
</body>
</html>